// source: klausapp.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.klausapp.CategoryScoreByInterval', null, global);
goog.exportSymbol('proto.klausapp.CategoryScoreByInterval.IntervalScore', null, global);
goog.exportSymbol('proto.klausapp.GetScoreChangePoPRequest', null, global);
goog.exportSymbol('proto.klausapp.OverallScore', null, global);
goog.exportSymbol('proto.klausapp.ScoreChangePoP', null, global);
goog.exportSymbol('proto.klausapp.TicketScoreByCategory', null, global);
goog.exportSymbol('proto.klausapp.TicketScoreByCategory.CategoryScore', null, global);
goog.exportSymbol('proto.klausapp.TimePeriod', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.klausapp.TimePeriod = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.klausapp.TimePeriod, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.klausapp.TimePeriod.displayName = 'proto.klausapp.TimePeriod';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.klausapp.CategoryScoreByInterval = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.klausapp.CategoryScoreByInterval.repeatedFields_, null);
};
goog.inherits(proto.klausapp.CategoryScoreByInterval, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.klausapp.CategoryScoreByInterval.displayName = 'proto.klausapp.CategoryScoreByInterval';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.klausapp.CategoryScoreByInterval.IntervalScore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.klausapp.CategoryScoreByInterval.IntervalScore.displayName = 'proto.klausapp.CategoryScoreByInterval.IntervalScore';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.klausapp.TicketScoreByCategory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.klausapp.TicketScoreByCategory.repeatedFields_, null);
};
goog.inherits(proto.klausapp.TicketScoreByCategory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.klausapp.TicketScoreByCategory.displayName = 'proto.klausapp.TicketScoreByCategory';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.klausapp.TicketScoreByCategory.CategoryScore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.klausapp.TicketScoreByCategory.CategoryScore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.klausapp.TicketScoreByCategory.CategoryScore.displayName = 'proto.klausapp.TicketScoreByCategory.CategoryScore';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.klausapp.OverallScore = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.klausapp.OverallScore, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.klausapp.OverallScore.displayName = 'proto.klausapp.OverallScore';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.klausapp.GetScoreChangePoPRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.klausapp.GetScoreChangePoPRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.klausapp.GetScoreChangePoPRequest.displayName = 'proto.klausapp.GetScoreChangePoPRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.klausapp.ScoreChangePoP = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.klausapp.ScoreChangePoP, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.klausapp.ScoreChangePoP.displayName = 'proto.klausapp.ScoreChangePoP';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.klausapp.TimePeriod.prototype.toObject = function(opt_includeInstance) {
  return proto.klausapp.TimePeriod.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.klausapp.TimePeriod} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.TimePeriod.toObject = function(includeInstance, msg) {
  var f, obj = {
    startdate: (f = msg.getStartdate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    enddate: (f = msg.getEnddate()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.klausapp.TimePeriod}
 */
proto.klausapp.TimePeriod.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.klausapp.TimePeriod;
  return proto.klausapp.TimePeriod.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.klausapp.TimePeriod} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.klausapp.TimePeriod}
 */
proto.klausapp.TimePeriod.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setStartdate(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEnddate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.klausapp.TimePeriod.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.klausapp.TimePeriod.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.klausapp.TimePeriod} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.TimePeriod.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartdate();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getEnddate();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.Timestamp startDate = 1;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.klausapp.TimePeriod.prototype.getStartdate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 1));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.klausapp.TimePeriod} returns this
*/
proto.klausapp.TimePeriod.prototype.setStartdate = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.klausapp.TimePeriod} returns this
 */
proto.klausapp.TimePeriod.prototype.clearStartdate = function() {
  return this.setStartdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.klausapp.TimePeriod.prototype.hasStartdate = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Timestamp endDate = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.klausapp.TimePeriod.prototype.getEnddate = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.klausapp.TimePeriod} returns this
*/
proto.klausapp.TimePeriod.prototype.setEnddate = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.klausapp.TimePeriod} returns this
 */
proto.klausapp.TimePeriod.prototype.clearEnddate = function() {
  return this.setEnddate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.klausapp.TimePeriod.prototype.hasEnddate = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.klausapp.CategoryScoreByInterval.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.klausapp.CategoryScoreByInterval.prototype.toObject = function(opt_includeInstance) {
  return proto.klausapp.CategoryScoreByInterval.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.klausapp.CategoryScoreByInterval} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.CategoryScoreByInterval.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ratingcount: jspb.Message.getFieldWithDefault(msg, 3, 0),
    scorebyintervalList: jspb.Message.toObjectList(msg.getScorebyintervalList(),
    proto.klausapp.CategoryScoreByInterval.IntervalScore.toObject, includeInstance),
    overallscore: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.klausapp.CategoryScoreByInterval}
 */
proto.klausapp.CategoryScoreByInterval.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.klausapp.CategoryScoreByInterval;
  return proto.klausapp.CategoryScoreByInterval.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.klausapp.CategoryScoreByInterval} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.klausapp.CategoryScoreByInterval}
 */
proto.klausapp.CategoryScoreByInterval.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRatingcount(value);
      break;
    case 4:
      var value = new proto.klausapp.CategoryScoreByInterval.IntervalScore;
      reader.readMessage(value,proto.klausapp.CategoryScoreByInterval.IntervalScore.deserializeBinaryFromReader);
      msg.addScorebyinterval(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setOverallscore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.klausapp.CategoryScoreByInterval.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.klausapp.CategoryScoreByInterval.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.klausapp.CategoryScoreByInterval} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.CategoryScoreByInterval.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRatingcount();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getScorebyintervalList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.klausapp.CategoryScoreByInterval.IntervalScore.serializeBinaryToWriter
    );
  }
  f = message.getOverallscore();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.prototype.toObject = function(opt_includeInstance) {
  return proto.klausapp.CategoryScoreByInterval.IntervalScore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.klausapp.CategoryScoreByInterval.IntervalScore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.toObject = function(includeInstance, msg) {
  var f, obj = {
    interval: jspb.Message.getFieldWithDefault(msg, 1, ""),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.klausapp.CategoryScoreByInterval.IntervalScore}
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.klausapp.CategoryScoreByInterval.IntervalScore;
  return proto.klausapp.CategoryScoreByInterval.IntervalScore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.klausapp.CategoryScoreByInterval.IntervalScore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.klausapp.CategoryScoreByInterval.IntervalScore}
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInterval(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.klausapp.CategoryScoreByInterval.IntervalScore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.klausapp.CategoryScoreByInterval.IntervalScore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInterval();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional string interval = 1;
 * @return {string}
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.prototype.getInterval = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.klausapp.CategoryScoreByInterval.IntervalScore} returns this
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.prototype.setInterval = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float score = 2;
 * @return {number}
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.klausapp.CategoryScoreByInterval.IntervalScore} returns this
 */
proto.klausapp.CategoryScoreByInterval.IntervalScore.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.klausapp.CategoryScoreByInterval.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.klausapp.CategoryScoreByInterval} returns this
 */
proto.klausapp.CategoryScoreByInterval.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.klausapp.CategoryScoreByInterval.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.klausapp.CategoryScoreByInterval} returns this
 */
proto.klausapp.CategoryScoreByInterval.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 ratingCount = 3;
 * @return {number}
 */
proto.klausapp.CategoryScoreByInterval.prototype.getRatingcount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.klausapp.CategoryScoreByInterval} returns this
 */
proto.klausapp.CategoryScoreByInterval.prototype.setRatingcount = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated IntervalScore scoreByInterval = 4;
 * @return {!Array<!proto.klausapp.CategoryScoreByInterval.IntervalScore>}
 */
proto.klausapp.CategoryScoreByInterval.prototype.getScorebyintervalList = function() {
  return /** @type{!Array<!proto.klausapp.CategoryScoreByInterval.IntervalScore>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.klausapp.CategoryScoreByInterval.IntervalScore, 4));
};


/**
 * @param {!Array<!proto.klausapp.CategoryScoreByInterval.IntervalScore>} value
 * @return {!proto.klausapp.CategoryScoreByInterval} returns this
*/
proto.klausapp.CategoryScoreByInterval.prototype.setScorebyintervalList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.klausapp.CategoryScoreByInterval.IntervalScore=} opt_value
 * @param {number=} opt_index
 * @return {!proto.klausapp.CategoryScoreByInterval.IntervalScore}
 */
proto.klausapp.CategoryScoreByInterval.prototype.addScorebyinterval = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.klausapp.CategoryScoreByInterval.IntervalScore, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.klausapp.CategoryScoreByInterval} returns this
 */
proto.klausapp.CategoryScoreByInterval.prototype.clearScorebyintervalList = function() {
  return this.setScorebyintervalList([]);
};


/**
 * optional float overallScore = 5;
 * @return {number}
 */
proto.klausapp.CategoryScoreByInterval.prototype.getOverallscore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.klausapp.CategoryScoreByInterval} returns this
 */
proto.klausapp.CategoryScoreByInterval.prototype.setOverallscore = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.klausapp.TicketScoreByCategory.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.klausapp.TicketScoreByCategory.prototype.toObject = function(opt_includeInstance) {
  return proto.klausapp.TicketScoreByCategory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.klausapp.TicketScoreByCategory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.TicketScoreByCategory.toObject = function(includeInstance, msg) {
  var f, obj = {
    ticketid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    categoryscoresList: jspb.Message.toObjectList(msg.getCategoryscoresList(),
    proto.klausapp.TicketScoreByCategory.CategoryScore.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.klausapp.TicketScoreByCategory}
 */
proto.klausapp.TicketScoreByCategory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.klausapp.TicketScoreByCategory;
  return proto.klausapp.TicketScoreByCategory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.klausapp.TicketScoreByCategory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.klausapp.TicketScoreByCategory}
 */
proto.klausapp.TicketScoreByCategory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTicketid(value);
      break;
    case 2:
      var value = new proto.klausapp.TicketScoreByCategory.CategoryScore;
      reader.readMessage(value,proto.klausapp.TicketScoreByCategory.CategoryScore.deserializeBinaryFromReader);
      msg.addCategoryscores(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.klausapp.TicketScoreByCategory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.klausapp.TicketScoreByCategory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.klausapp.TicketScoreByCategory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.TicketScoreByCategory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTicketid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCategoryscoresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.klausapp.TicketScoreByCategory.CategoryScore.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.prototype.toObject = function(opt_includeInstance) {
  return proto.klausapp.TicketScoreByCategory.CategoryScore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.klausapp.TicketScoreByCategory.CategoryScore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.klausapp.TicketScoreByCategory.CategoryScore}
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.klausapp.TicketScoreByCategory.CategoryScore;
  return proto.klausapp.TicketScoreByCategory.CategoryScore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.klausapp.TicketScoreByCategory.CategoryScore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.klausapp.TicketScoreByCategory.CategoryScore}
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.klausapp.TicketScoreByCategory.CategoryScore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.klausapp.TicketScoreByCategory.CategoryScore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.klausapp.TicketScoreByCategory.CategoryScore} returns this
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float score = 2;
 * @return {number}
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.klausapp.TicketScoreByCategory.CategoryScore} returns this
 */
proto.klausapp.TicketScoreByCategory.CategoryScore.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional int32 ticketId = 1;
 * @return {number}
 */
proto.klausapp.TicketScoreByCategory.prototype.getTicketid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.klausapp.TicketScoreByCategory} returns this
 */
proto.klausapp.TicketScoreByCategory.prototype.setTicketid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated CategoryScore categoryScores = 2;
 * @return {!Array<!proto.klausapp.TicketScoreByCategory.CategoryScore>}
 */
proto.klausapp.TicketScoreByCategory.prototype.getCategoryscoresList = function() {
  return /** @type{!Array<!proto.klausapp.TicketScoreByCategory.CategoryScore>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.klausapp.TicketScoreByCategory.CategoryScore, 2));
};


/**
 * @param {!Array<!proto.klausapp.TicketScoreByCategory.CategoryScore>} value
 * @return {!proto.klausapp.TicketScoreByCategory} returns this
*/
proto.klausapp.TicketScoreByCategory.prototype.setCategoryscoresList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.klausapp.TicketScoreByCategory.CategoryScore=} opt_value
 * @param {number=} opt_index
 * @return {!proto.klausapp.TicketScoreByCategory.CategoryScore}
 */
proto.klausapp.TicketScoreByCategory.prototype.addCategoryscores = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.klausapp.TicketScoreByCategory.CategoryScore, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.klausapp.TicketScoreByCategory} returns this
 */
proto.klausapp.TicketScoreByCategory.prototype.clearCategoryscoresList = function() {
  return this.setCategoryscoresList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.klausapp.OverallScore.prototype.toObject = function(opt_includeInstance) {
  return proto.klausapp.OverallScore.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.klausapp.OverallScore} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.OverallScore.toObject = function(includeInstance, msg) {
  var f, obj = {
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.klausapp.OverallScore}
 */
proto.klausapp.OverallScore.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.klausapp.OverallScore;
  return proto.klausapp.OverallScore.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.klausapp.OverallScore} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.klausapp.OverallScore}
 */
proto.klausapp.OverallScore.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.klausapp.OverallScore.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.klausapp.OverallScore.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.klausapp.OverallScore} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.OverallScore.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
};


/**
 * optional float score = 1;
 * @return {number}
 */
proto.klausapp.OverallScore.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.klausapp.OverallScore} returns this
 */
proto.klausapp.OverallScore.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.klausapp.GetScoreChangePoPRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.klausapp.GetScoreChangePoPRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.klausapp.GetScoreChangePoPRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.GetScoreChangePoPRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    firstperiod: (f = msg.getFirstperiod()) && proto.klausapp.TimePeriod.toObject(includeInstance, f),
    secondperiod: (f = msg.getSecondperiod()) && proto.klausapp.TimePeriod.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.klausapp.GetScoreChangePoPRequest}
 */
proto.klausapp.GetScoreChangePoPRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.klausapp.GetScoreChangePoPRequest;
  return proto.klausapp.GetScoreChangePoPRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.klausapp.GetScoreChangePoPRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.klausapp.GetScoreChangePoPRequest}
 */
proto.klausapp.GetScoreChangePoPRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.klausapp.TimePeriod;
      reader.readMessage(value,proto.klausapp.TimePeriod.deserializeBinaryFromReader);
      msg.setFirstperiod(value);
      break;
    case 2:
      var value = new proto.klausapp.TimePeriod;
      reader.readMessage(value,proto.klausapp.TimePeriod.deserializeBinaryFromReader);
      msg.setSecondperiod(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.klausapp.GetScoreChangePoPRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.klausapp.GetScoreChangePoPRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.klausapp.GetScoreChangePoPRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.GetScoreChangePoPRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFirstperiod();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.klausapp.TimePeriod.serializeBinaryToWriter
    );
  }
  f = message.getSecondperiod();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.klausapp.TimePeriod.serializeBinaryToWriter
    );
  }
};


/**
 * optional TimePeriod firstPeriod = 1;
 * @return {?proto.klausapp.TimePeriod}
 */
proto.klausapp.GetScoreChangePoPRequest.prototype.getFirstperiod = function() {
  return /** @type{?proto.klausapp.TimePeriod} */ (
    jspb.Message.getWrapperField(this, proto.klausapp.TimePeriod, 1));
};


/**
 * @param {?proto.klausapp.TimePeriod|undefined} value
 * @return {!proto.klausapp.GetScoreChangePoPRequest} returns this
*/
proto.klausapp.GetScoreChangePoPRequest.prototype.setFirstperiod = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.klausapp.GetScoreChangePoPRequest} returns this
 */
proto.klausapp.GetScoreChangePoPRequest.prototype.clearFirstperiod = function() {
  return this.setFirstperiod(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.klausapp.GetScoreChangePoPRequest.prototype.hasFirstperiod = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional TimePeriod secondPeriod = 2;
 * @return {?proto.klausapp.TimePeriod}
 */
proto.klausapp.GetScoreChangePoPRequest.prototype.getSecondperiod = function() {
  return /** @type{?proto.klausapp.TimePeriod} */ (
    jspb.Message.getWrapperField(this, proto.klausapp.TimePeriod, 2));
};


/**
 * @param {?proto.klausapp.TimePeriod|undefined} value
 * @return {!proto.klausapp.GetScoreChangePoPRequest} returns this
*/
proto.klausapp.GetScoreChangePoPRequest.prototype.setSecondperiod = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.klausapp.GetScoreChangePoPRequest} returns this
 */
proto.klausapp.GetScoreChangePoPRequest.prototype.clearSecondperiod = function() {
  return this.setSecondperiod(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.klausapp.GetScoreChangePoPRequest.prototype.hasSecondperiod = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.klausapp.ScoreChangePoP.prototype.toObject = function(opt_includeInstance) {
  return proto.klausapp.ScoreChangePoP.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.klausapp.ScoreChangePoP} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.ScoreChangePoP.toObject = function(includeInstance, msg) {
  var f, obj = {
    scorechange: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.klausapp.ScoreChangePoP}
 */
proto.klausapp.ScoreChangePoP.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.klausapp.ScoreChangePoP;
  return proto.klausapp.ScoreChangePoP.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.klausapp.ScoreChangePoP} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.klausapp.ScoreChangePoP}
 */
proto.klausapp.ScoreChangePoP.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScorechange(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.klausapp.ScoreChangePoP.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.klausapp.ScoreChangePoP.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.klausapp.ScoreChangePoP} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.klausapp.ScoreChangePoP.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScorechange();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
};


/**
 * optional float scoreChange = 1;
 * @return {number}
 */
proto.klausapp.ScoreChangePoP.prototype.getScorechange = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.klausapp.ScoreChangePoP} returns this
 */
proto.klausapp.ScoreChangePoP.prototype.setScorechange = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


goog.object.extend(exports, proto.klausapp);
